### ISSUE TITLE
 Unable to place sideways signs (from homedecor_modpack split)

### ISSUE THREAD

**Issue by redblade7** [VanessaE/signs_lib#1]
The issue here was closed as part of the splitting off of signs_lib from homedecor_modpack

https://github.com/VanessaE/homedecor_modpack/issues/298

**Comment by VanessaE** [comment]
I explained in the signs_lib forum thread how to go about placing those perpendicular and back-to-back signs.  You're basically arguing with an engine bug, not a bug in signs_lib.
