### ISSUE TITLE
Changes to Default Signs Affects Texture of Wood Sign

### ISSUE THREAD

**Issue by LazyJ** [VanessaE/signs_lib#3]
Minetest Game commit [aa676ab](https://github.com/minetest/minetest_game/commit/aa676ab87863a8d42050d56355db1b25e07ce4bd) changed the node name of the default signs. The result is a colored square for the former default sign is displayed in the inventory (dummy image) but when place the signs_lib version appears and works as before.

**Comment by VanessaE** [comment]
2f2f1e4b0a120e23e354f39fdb2fbc9c98c0401d
